// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: executor/v1/executor.proto

// Package executor.v1 defines the internal contract between the api-gateway
// and the executor service, which runs untrusted user code in isolated
// sandboxes.
//
// The contract is deliberately request/response shaped: in the MVP the
// gateway calls Execute synchronously, and in Phase 7 the same message types
// ride a Redis-backed queue without the executor's core changing.

package executorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Language enumerates the runtimes the executor ships sandbox images for.
type Language int32

const (
	Language_LANGUAGE_UNSPECIFIED Language = 0
	Language_LANGUAGE_CPP         Language = 1
	Language_LANGUAGE_PYTHON      Language = 2
	Language_LANGUAGE_GO          Language = 3
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANGUAGE_UNSPECIFIED",
		1: "LANGUAGE_CPP",
		2: "LANGUAGE_PYTHON",
		3: "LANGUAGE_GO",
	}
	Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"LANGUAGE_CPP":         1,
		"LANGUAGE_PYTHON":      2,
		"LANGUAGE_GO":          3,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_executor_v1_executor_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_executor_v1_executor_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{0}
}

// Verdict is the outcome of judging one execution, mirroring standard
// competitive-programming judge semantics.
type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	// The program ran successfully and its output matched expected_output.
	Verdict_VERDICT_ACCEPTED Verdict = 1
	// The program ran successfully but its output did not match.
	Verdict_VERDICT_WRONG_ANSWER Verdict = 2
	// The program exited non-zero or crashed (signal, uncaught exception).
	Verdict_VERDICT_RUNTIME_ERROR Verdict = 3
	// The source code failed to compile (C++/Go) or parse (Python).
	Verdict_VERDICT_COMPILATION_ERROR Verdict = 4
	// The program exceeded the wall-clock time limit and was killed.
	Verdict_VERDICT_TIME_LIMIT_EXCEEDED Verdict = 5
	// The program exceeded the memory limit and was killed.
	Verdict_VERDICT_MEMORY_LIMIT_EXCEEDED Verdict = 6
	// The executor itself failed; the submission should be retried, not judged.
	Verdict_VERDICT_INTERNAL_ERROR Verdict = 7
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_ACCEPTED",
		2: "VERDICT_WRONG_ANSWER",
		3: "VERDICT_RUNTIME_ERROR",
		4: "VERDICT_COMPILATION_ERROR",
		5: "VERDICT_TIME_LIMIT_EXCEEDED",
		6: "VERDICT_MEMORY_LIMIT_EXCEEDED",
		7: "VERDICT_INTERNAL_ERROR",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED":           0,
		"VERDICT_ACCEPTED":              1,
		"VERDICT_WRONG_ANSWER":          2,
		"VERDICT_RUNTIME_ERROR":         3,
		"VERDICT_COMPILATION_ERROR":     4,
		"VERDICT_TIME_LIMIT_EXCEEDED":   5,
		"VERDICT_MEMORY_LIMIT_EXCEEDED": 6,
		"VERDICT_INTERNAL_ERROR":        7,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_executor_v1_executor_proto_enumTypes[1].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_executor_v1_executor_proto_enumTypes[1]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{1}
}

// ExecuteRequest carries one piece of source code and one test case.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source code, UTF-8. Size limits are enforced server-side.
	Code     string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language Language `protobuf:"varint,2,opt,name=language,proto3,enum=executor.v1.Language" json:"language,omitempty"`
	// Data piped to the program's standard input.
	Stdin string `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	// Expected standard output; comparison ignores trailing whitespace per line.
	ExpectedOutput string `protobuf:"bytes,4,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	// Wall-clock limit in milliseconds. Zero means the server default.
	// The executor clamps this to its configured hard maximum.
	TimeLimitMs uint32 `protobuf:"varint,5,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	// Memory limit in megabytes. Zero means the server default.
	// The executor clamps this to its configured hard maximum.
	MemoryLimitMb uint32 `protobuf:"varint,6,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *ExecuteRequest) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *ExecuteRequest) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

func (x *ExecuteRequest) GetTimeLimitMs() uint32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *ExecuteRequest) GetMemoryLimitMb() uint32 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

// ExecuteResponse reports the judged outcome of one execution.
type ExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Verdict Verdict                `protobuf:"varint,1,opt,name=verdict,proto3,enum=executor.v1.Verdict" json:"verdict,omitempty"`
	// Program output, truncated server-side to a sane maximum.
	Stdout string `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr string `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Exit code of the user process; meaningful for RUNTIME_ERROR diagnostics.
	ExitCode int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Observed wall-clock runtime in milliseconds.
	TimeUsedMs uint32 `protobuf:"varint,5,opt,name=time_used_ms,json=timeUsedMs,proto3" json:"time_used_ms,omitempty"`
	// Peak memory usage in kilobytes, when the sandbox can report it.
	MemoryUsedKb uint32 `protobuf:"varint,6,opt,name=memory_used_kb,json=memoryUsedKb,proto3" json:"memory_used_kb,omitempty"`
	// Compiler diagnostics; populated for COMPILATION_ERROR.
	CompileOutput string `protobuf:"bytes,7,opt,name=compile_output,json=compileOutput,proto3" json:"compile_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_executor_v1_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetTimeUsedMs() uint32 {
	if x != nil {
		return x.TimeUsedMs
	}
	return 0
}

func (x *ExecuteResponse) GetMemoryUsedKb() uint32 {
	if x != nil {
		return x.MemoryUsedKb
	}
	return 0
}

func (x *ExecuteResponse) GetCompileOutput() string {
	if x != nil {
		return x.CompileOutput
	}
	return ""
}

var File_executor_v1_executor_proto protoreflect.FileDescriptor

const file_executor_v1_executor_proto_rawDesc = "" +
	"\n" +
	"\x1aexecutor/v1/executor.proto\x12\vexecutor.v1\"\xe2\x01\n" +
	"\x0eExecuteRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x121\n" +
	"\blanguage\x18\x02 \x01(\x0e2\x15.executor.v1.LanguageR\blanguage\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\x12'\n" +
	"\x0fexpected_output\x18\x04 \x01(\tR\x0eexpectedOutput\x12\"\n" +
	"\rtime_limit_ms\x18\x05 \x01(\rR\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_mb\x18\x06 \x01(\rR\rmemoryLimitMb\"\xfd\x01\n" +
	"\x0fExecuteResponse\x12.\n" +
	"\averdict\x18\x01 \x01(\x0e2\x14.executor.v1.VerdictR\averdict\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12 \n" +
	"\ftime_used_ms\x18\x05 \x01(\rR\n" +
	"timeUsedMs\x12$\n" +
	"\x0ememory_used_kb\x18\x06 \x01(\rR\fmemoryUsedKb\x12%\n" +
	"\x0ecompile_output\x18\a \x01(\tR\rcompileOutput*\\\n" +
	"\bLanguage\x12\x18\n" +
	"\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fLANGUAGE_CPP\x10\x01\x12\x13\n" +
	"\x0fLANGUAGE_PYTHON\x10\x02\x12\x0f\n" +
	"\vLANGUAGE_GO\x10\x03*\xec\x01\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VERDICT_ACCEPTED\x10\x01\x12\x18\n" +
	"\x14VERDICT_WRONG_ANSWER\x10\x02\x12\x19\n" +
	"\x15VERDICT_RUNTIME_ERROR\x10\x03\x12\x1d\n" +
	"\x19VERDICT_COMPILATION_ERROR\x10\x04\x12\x1f\n" +
	"\x1bVERDICT_TIME_LIMIT_EXCEEDED\x10\x05\x12!\n" +
	"\x1dVERDICT_MEMORY_LIMIT_EXCEEDED\x10\x06\x12\x1a\n" +
	"\x16VERDICT_INTERNAL_ERROR\x10\a2W\n" +
	"\x0fExecutorService\x12D\n" +
	"\aExecute\x12\x1b.executor.v1.ExecuteRequest\x1a\x1c.executor.v1.ExecuteResponseB\xab\x01\n" +
	"\x0fcom.executor.v1B\rExecutorProtoP\x01Z<github.com/caezu/arena/backend/pkg/pb/executor/v1;executorv1\xa2\x02\x03EXX\xaa\x02\vExecutor.V1\xca\x02\vExecutor\\V1\xe2\x02\x17Executor\\V1\\GPBMetadata\xea\x02\fExecutor::V1b\x06proto3"

var (
	file_executor_v1_executor_proto_rawDescOnce sync.Once
	file_executor_v1_executor_proto_rawDescData []byte
)

func file_executor_v1_executor_proto_rawDescGZIP() []byte {
	file_executor_v1_executor_proto_rawDescOnce.Do(func() {
		file_executor_v1_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_v1_executor_proto_rawDesc), len(file_executor_v1_executor_proto_rawDesc)))
	})
	return file_executor_v1_executor_proto_rawDescData
}

var file_executor_v1_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_executor_v1_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_executor_v1_executor_proto_goTypes = []any{
	(Language)(0),           // 0: executor.v1.Language
	(Verdict)(0),            // 1: executor.v1.Verdict
	(*ExecuteRequest)(nil),  // 2: executor.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 3: executor.v1.ExecuteResponse
}
var file_executor_v1_executor_proto_depIdxs = []int32{
	0, // 0: executor.v1.ExecuteRequest.language:type_name -> executor.v1.Language
	1, // 1: executor.v1.ExecuteResponse.verdict:type_name -> executor.v1.Verdict
	2, // 2: executor.v1.ExecutorService.Execute:input_type -> executor.v1.ExecuteRequest
	3, // 3: executor.v1.ExecutorService.Execute:output_type -> executor.v1.ExecuteResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_executor_v1_executor_proto_init() }
func file_executor_v1_executor_proto_init() {
	if File_executor_v1_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_v1_executor_proto_rawDesc), len(file_executor_v1_executor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_v1_executor_proto_goTypes,
		DependencyIndexes: file_executor_v1_executor_proto_depIdxs,
		EnumInfos:         file_executor_v1_executor_proto_enumTypes,
		MessageInfos:      file_executor_v1_executor_proto_msgTypes,
	}.Build()
	File_executor_v1_executor_proto = out.File
	file_executor_v1_executor_proto_goTypes = nil
	file_executor_v1_executor_proto_depIdxs = nil
}
